# Generated by Django 4.2.11 on 2024-03-25 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervalAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IntervalsExerciseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowest_octave', models.IntegerField()),
                ('highest_octave', models.IntegerField()),
                ('allowed_intervals', models.ManyToManyField(to='exercises.interval')),
            ],
        ),
        migrations.CreateModel(
            name='IntervalsExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.ManyToManyField(related_name='exercises_with_interval_instance_as_answer', through='exercises.IntervalAnswer', to='exercises.intervalinstance')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises_with_interval_instance_as_question', to='exercises.intervalinstance')),
                ('settings', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercise', to='exercises.intervalsexercisesettings')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='intervalanswer',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.intervalsexercise'),
        ),
        migrations.AddField(
            model_name='intervalanswer',
            name='interval_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.intervalinstance'),
        ),
    ]
