# Generated by Django 4.2.11 on 2024-03-25 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_intervalanswer_intervalsexercisesettings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interval',
            options={'ordering': ['num_semitones']},
        ),
    ]
