# Generated by Django 4.2.11 on 2024-03-25 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_intervalsexercisescore_intervalsexercise_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IntervalsExerciseScore',
            new_name='ExerciseScore',
        ),
    ]
