# Generated by Django 4.2.11 on 2024-04-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_rename_intervalsexercisescore_exercisescore'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='intervalinstance',
            constraint=models.UniqueConstraint(fields=('start_note', 'interval'), name='interval_instance_is_defined_by_interval_and_start_note'),
        ),
    ]
