# Generated by Django 4.2.11 on 2024-04-04 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_intervalinstance_interval_instance_is_defined_by_interval_and_start_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalsexercise',
            name='score',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercises.exercisescore'),
        ),
    ]
