# Generated by Django 4.2.11 on 2024-04-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_alter_intervalsexercise_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='interval',
            name='interval_type',
            field=models.IntegerField(choices=[(0, 'harmonic'), (1, 'melodic ascending'), (2, 'melodic descending')], default=0),
        ),
    ]
