# Generated by Django 4.2.11 on 2024-04-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_interval_interval_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='interval',
            constraint=models.UniqueConstraint(fields=('num_semitones', 'interval_type'), name='interval_is_defined_by_num_semitones_and_type'),
        ),
    ]
