# Generated by Django 4.2.11 on 2024-04-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_alter_intervalsexercisesettings_lowest_octave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalsexercisesettings',
            name='highest_octave',
            field=models.IntegerField(help_text='change range of notes played (e.g. to practice with high pitches only, low pitches only, or with full range of notes)'),
        ),
    ]
