# Generated by Django 4.2.11 on 2024-04-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_alter_intervalsexercisesettings_highest_octave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalsexercisesettings',
            name='highest_octave',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='intervalsexercisesettings',
            name='lowest_octave',
            field=models.IntegerField(),
        ),
    ]
