# Generated by Django 4.2.11 on 2024-04-23 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0012_alter_intervalsexercisesettings_highest_octave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalsexercisesettings',
            name='highest_octave',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AlterField(
            model_name='intervalsexercisesettings',
            name='lowest_octave',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(-1)]),
        ),
    ]
